### ISSUE TITLE
Issue for workaround 

### ISSUE THREAD

**Issue by Expecho** [z1c0/otel-dotnet-blazor#2]
Hi, I read this in your blogpost:

> I will probably raise some GitHub issues for file PRs for the issues I had to workaround now and then we will see if this triggers discussion and thoughts towards Blazor, WebAssembly and OpenTelemetry.

Did you raise an issue to fix the workaround yet, if so do you have a link for me? If not, are you still planning to do so?

**Comment by z1c0** [comment]
Sorry, I never followed up on this.

**Comment by Expecho** [comment]
Thanks. Found out there are already issues raised, like [this one](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2816)
